---
title: "Gapminder Data"
author: "Tanner Gildea"
date: "3/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(cache = TRUE)

library(tidyverse)
library(gapminder)
library(ggplot2)
library(gganimate)

```

```{r visualize}
gapminder %>% 
  mutate(continent = fct_collapse(continent,
                                  Asia =  c("Asia", "Oceania"))) %>% 
  
  filter(continent %in% c("Americas", "Africa", "Asia")) %>% 
  
  # changes order of continents in columns
  mutate(continent = fct_relevel(continent, c("Americas", "Africa", "Asia"))) %>% 
  
  ggplot(aes(x = gdpPercap, y = lifeExp, size = pop, color = country)) + 
  geom_point(alpha = .7, show.legend = FALSE) + 
  
  facet_wrap(~continent) + 
  
  scale_colour_manual(values = country_colors) +
  
  # makes x-axis scale more accessible
  scale_x_log10(breaks = c(1000,10000), labels = c("$1,000", "$10,000")) +
  
  # using {} within title allows variable year to change
  labs(title = "The World Gets Better Every Year: {frame_time}",
         caption = "Source: gapminder package",
       x = "GDP Per Capita",
       y = "Life Expectancy") +
  
  # gganimate part
  transition_time(year) +
  ease_aes('linear')

```

